### ISSUE TITLE
Ionic 4 Angular 8 doesn't work with the given guidance

### ISSUE THREAD

**Issue by Sampath-Lokuge** [coturiv/ionic-typeorm-starter#9]
Hi,

Error:

```
> ionic serve
> ng.cmd run app:serve --host=localhost --port=8100
[ng] An unhandled exception occurred: Cannot find builder "@angular-builders/custom-webpack:dev-server".
[ng] See "C:\Users\Sampath\AppData\Local\Temp\ng-A7U3I7\angular-errors.log" for further details.

[ERROR] ng has unexpectedly closed (exit code 127).

        The Ionic CLI will exit. Please check any output above for error details.
```

_package.json_

```
{
  "name": "mobileAssetManager",
  "version": "0.0.1",
  "author": "PropelApps",
  "homepage": "https://www.propelapps.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-builders/dev-server": "^7.3.1",
    "@angular/common": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@capacitor/android": "^1.4.0",
    "@capacitor/core": "1.4.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.7.1",
    "cordova-sqlite-storage": "^4.0.0",
    "core-js": "^2.5.4",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.1",
    "sql.js": "^0.5.0",
    "tslib": "^1.9.0",
    "typeorm": "^0.2.22",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^7.5.2",
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.3.25",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "1.4.0",
    "@ionic/angular-toolkit": "^2.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {}
    }
  }
}
```

More details:

```
[error] Error: Could not find the implementation for builder @angular-builders/dev-server:generic
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (D:\Clients\abc\mobile-asset-manager\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:19)
    at RunCommand.runSingleTarget (D:\Clients\abc\mobile-asset-manager\node_modules\@angular\cli\models\architect-command.js:177:55)
    at async RunCommand.runArchitectTarget (D:\Clients\abc\mobile-asset-manager\node_modules\@angular\cli\models\architect-command.js:219:24)
```

**Comment by coturiv** [comment]
You can follow this guide.
https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#migration-from-version-7-to-version-8

**Comment by Sampath-Lokuge** [comment]
Hi @coturiv 
I have tried to do that. But it was huge complex thing. Now Ionic 5 and Angular 9 is out. Can you create a new Ionic 5 with the TypeORM template here?

**Comment by coturiv** [comment]
All dependencies are updated with the latest versions 😄

**Comment by Sampath-Lokuge** [comment]
@coturiv Oh.. Amazing! Thanks a lot!
